import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * MVP schema. Deliberately a subset of docs/ARCHITECTURE.md §3.
 *
 * The one structural decision carried over in full, because everything about
 * cost depends on it: GENERATIONS ARE SHARED AND IMMUTABLE, PROJECTS ARE
 * FORKED AND MUTABLE. Two users submitting the same video share one
 * `generations` row and get their own `projects` + `diagrams` rows.
 *
 * Not here yet (see the architecture doc): auth/users, workspaces, credits,
 * annotations, versions, sharing, flashcards. `deviceId` stands in for a user
 * until Google sign-in lands; every table that will eventually key off a user
 * keys off `deviceId` today, so the migration is a backfill, not a redesign.
 */
export default defineSchema({
  sources: defineTable({
    kind: v.literal("youtube"),
    externalId: v.string(), // canonical YouTube video id
    canonicalUrl: v.string(),
    title: v.string(),
    author: v.optional(v.string()),
    thumbnailUrl: v.optional(v.string()),
    durationSec: v.optional(v.number()),
    requestCount: v.number(),
    lastRequestedAt: v.number(),
    createdAt: v.number(),
  }).index("by_external", ["kind", "externalId"]),

  transcripts: defineTable({
    sourceId: v.id("sources"),
    language: v.string(),
    // MVP: text inline. Convex caps documents at 1MB, so anything longer than
    // ~800KB is truncated at write time (see generate.ts). Move to _storage
    // when we support 3h lectures.
    text: v.string(),
    contentHash: v.string(),
    charCount: v.number(),
    isAutoGenerated: v.boolean(),
    provider: v.string(),
    createdAt: v.number(),
  })
    .index("by_source_lang", ["sourceId", "language"])
    .index("by_hash", ["contentHash"]),

  generations: defineTable({
    // sha256(externalId | transcriptHash | promptVersion | model | depth | lang)
    cacheKey: v.string(),
    sourceId: v.id("sources"),
    transcriptId: v.optional(v.id("transcripts")),

    promptVersion: v.string(),
    provider: v.string(),
    model: v.string(),

    status: v.union(
      v.literal("queued"),
      v.literal("transcribing"),
      v.literal("generating"),
      v.literal("validating"),
      v.literal("complete"),
      v.literal("failed"),
    ),
    stage: v.string(), // user-facing progress line
    failureCode: v.optional(v.string()),
    failureMessage: v.optional(v.string()),

    diagrams: v.optional(
      v.array(
        v.object({
          index: v.number(),
          title: v.string(),
          diagramType: v.string(),
          revealMode: v.union(v.literal("steps"), v.literal("atomic")),
          mermaid: v.string(),
          narration: v.array(v.string()),
          summary: v.optional(v.string()),
          validated: v.boolean(),
          repairs: v.array(v.string()),
        }),
      ),
    ),

    inputTokens: v.number(),
    outputTokens: v.number(),
    durationMs: v.number(),
    reuseCount: v.number(),
    lastUsedAt: v.number(),
    createdAt: v.number(),
  })
    .index("by_cache_key", ["cacheKey"])
    .index("by_source", ["sourceId"]),

  projects: defineTable({
    deviceId: v.string(), // → userId once auth lands
    sourceId: v.id("sources"),
    generationId: v.id("generations"),
    title: v.string(),
    thumbnailUrl: v.optional(v.string()),
    lastOpenedAt: v.number(),
    createdAt: v.number(),
  })
    .index("by_device", ["deviceId", "lastOpenedAt"])
    .index("by_device_generation", ["deviceId", "generationId"]),

  diagrams: defineTable({
    projectId: v.id("projects"),
    order: v.number(),
    title: v.string(),
    diagramType: v.string(),
    revealMode: v.union(v.literal("steps"), v.literal("atomic")),
    mermaid: v.string(),
    narration: v.array(v.string()),
    summary: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_project", ["projectId", "order"]),

  // Crude anonymous abuse control until auth + credits exist.
  usage: defineTable({
    deviceId: v.string(),
    day: v.string(), // YYYY-MM-DD (UTC)
    generations: v.number(),
  }).index("by_device_day", ["deviceId", "day"]),
});
