/* =========================================================
   YouTube transcript acquisition — provider chain.

   WHY A CHAIN: Convex functions run on Convex's cloud egress, whose IPs are
   shared across many customers. YouTube rate-limits per IP, so the watch-page
   scrape that works from a laptop returns 429 almost immediately from a cloud
   deployment. That is not a bug to retry away — the budget is already spent by
   the time our request arrives.

   So we try, in order:
     1. InnerTube player API, ANDROID client  — a real JSON endpoint, separate
        budget from the HTML page, no bot-check interstitial
     2. InnerTube player API, WEB client      — different quota again
     3. Watch-page HTML scrape                — the original approach
     4. (caller) user-supplied transcript     — always works, never blocked

   If all four are needed regularly in production, the answer is a commercial
   caption API or residential proxy — docs/ARCHITECTURE.md §7. This chain buys
   a working MVP, not a permanent solution.
========================================================= */

export type TranscriptResult = {
  text: string;
  language: string;
  isAutoGenerated: boolean;
  provider: string;
};

export class TranscriptError extends Error {
  code: string;
  constructor(code: string, message: string) {
    super(message);
    this.code = code;
  }
}

export type FetchResult = TranscriptResult & {
  title?: string;
  author?: string;
  durationSec?: number;
  thumbnailUrl: string;
};

const WEB_UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

/* ---------------------------------------------------------
   URL handling
--------------------------------------------------------- */

/**
 * Normalize any YouTube URL shape to a canonical 11-char video id.
 * Handles watch?v=, youtu.be/, /shorts/, /live/, /embed/, and bare ids.
 * Getting this wrong silently halves the cache hit rate.
 */
export function extractVideoId(input: string): string | null {
  const raw = String(input ?? "").trim();
  if (!raw) return null;

  if (/^[A-Za-z0-9_-]{11}$/.test(raw)) return raw;

  let url: URL;
  try {
    url = new URL(raw.startsWith("http") ? raw : `https://${raw}`);
  } catch {
    return null;
  }

  const host = url.hostname.replace(/^www\.|^m\./, "");
  const path = url.pathname;

  if (host === "youtu.be") {
    const id = path.slice(1).split("/")[0];
    return /^[A-Za-z0-9_-]{11}$/.test(id) ? id : null;
  }

  if (host === "youtube.com" || host === "youtube-nocookie.com") {
    const q = url.searchParams.get("v");
    if (q && /^[A-Za-z0-9_-]{11}$/.test(q)) return q;
    const m = path.match(/^\/(shorts|live|embed|v)\/([A-Za-z0-9_-]{11})/);
    if (m) return m[2];
  }

  return null;
}

export function canonicalUrl(videoId: string) {
  return `https://www.youtube.com/watch?v=${videoId}`;
}

/* ---------------------------------------------------------
   Parsing helpers
--------------------------------------------------------- */

/** YouTube double-encodes entities in caption text, so decode twice. */
function decodeEntities(s: string): string {
  const once = (t: string) =>
    t
      .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
      .replace(/&#x([0-9a-fA-F]+);/g, (_, h) => String.fromCharCode(parseInt(h, 16)))
      .replace(/&quot;/g, '"')
      .replace(/&apos;/g, "'")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&");
  return once(once(s));
}

type CaptionTrack = {
  baseUrl: string;
  languageCode?: string;
  kind?: string; // "asr" = auto-generated
};

function pickTrack(tracks: CaptionTrack[], preferred = "en"): CaptionTrack | null {
  if (!tracks?.length) return null;
  return (
    tracks.find((t) => t.languageCode === preferred && t.kind !== "asr") ||
    tracks.find((t) => t.languageCode?.startsWith(preferred) && t.kind !== "asr") ||
    tracks.find((t) => t.languageCode?.startsWith(preferred)) ||
    tracks.find((t) => t.kind !== "asr") ||
    tracks[0]
  );
}

/** No DOMParser in the Convex runtime, so the caption XML is regex-parsed. */
function parseCaptionXml(xml: string): string {
  const out: string[] = [];
  const re = /<text\b[^>]*>([\s\S]*?)<\/text>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) {
    const t = decodeEntities(m[1])
      .replace(/<[^>]+>/g, "")
      .replace(/\s+/g, " ")
      .trim();
    if (t) out.push(t);
  }
  return out.join(" ");
}

/** json3 is the more reliable caption format — no entity double-encoding. */
function parseCaptionJson3(body: string): string {
  try {
    const json = JSON.parse(body);
    const out: string[] = [];
    for (const ev of json?.events ?? []) {
      const line = (ev?.segs ?? [])
        .map((s: any) => s?.utf8 ?? "")
        .join("")
        .replace(/\s+/g, " ")
        .trim();
      if (line) out.push(line);
    }
    return out.join(" ");
  } catch {
    return "";
  }
}

/** Fetch a caption track, preferring json3 and falling back to XML. */
async function downloadCaptions(baseUrl: string): Promise<string> {
  const url = decodeEntities(baseUrl);

  const json3 = url.includes("fmt=") ? url : `${url}&fmt=json3`;
  const a = await fetch(json3, { headers: { "User-Agent": WEB_UA } });
  if (a.ok) {
    const text = parseCaptionJson3(await a.text());
    if (text) return text;
  }

  const b = await fetch(url, { headers: { "User-Agent": WEB_UA } });
  if (!b.ok) {
    throw new TranscriptError(
      b.status === 429 ? "RATE_LIMITED" : "CAPTION_FETCH_FAILED",
      `Caption download failed with ${b.status}.`,
    );
  }
  return parseCaptionXml(await b.text());
}

function assertUsable(text: string, videoId: string): void {
  if (text.split(/\s+/).filter(Boolean).length < 120) {
    throw new TranscriptError(
      "TRANSCRIPT_TOO_SHORT",
      "There isn't enough spoken content in this video to map.",
    );
  }
}

function thumb(videoId: string) {
  return `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;
}

/* ---------------------------------------------------------
   Provider 1: your own transcript proxy (optional, recommended)

   The watch-page scrape works reliably from a RESIDENTIAL IP and returns 429
   almost immediately from Convex's shared cloud egress. So run the fetch
   somewhere with a residential IP and point Convex at it:

     node scripts/transcript-proxy.mjs        # on your machine
     cloudflared tunnel --url http://localhost:8799
     npx convex env set TRANSCRIPT_PROXY_URL https://<tunnel>.trycloudflare.com
     npx convex env set TRANSCRIPT_PROXY_TOKEN <the token the script prints>

   Any endpoint works as long as GET ?videoId=<id> returns
   { text, language?, isAutoGenerated?, title?, author?, durationSec? }.
   Swap in a commercial caption API here when you outgrow the local proxy.

   NOTE: InnerTube (youtubei/v1/player) was tried and removed. With the public
   web key it returns 400 for ANDROID/IOS clients and UNPLAYABLE for WEB, even
   from a clean residential IP — it now requires attestation tokens. It only
   added two guaranteed-failing round trips before the provider that works.
--------------------------------------------------------- */

async function fetchViaProxy(videoId: string): Promise<FetchResult> {
  const base = process.env.TRANSCRIPT_PROXY_URL;
  if (!base) throw new TranscriptError("NO_PROXY", "No transcript proxy configured.");

  const token = process.env.TRANSCRIPT_PROXY_TOKEN;
  const res = await fetch(
    `${base.replace(/\/$/, "")}/transcript?videoId=${encodeURIComponent(videoId)}`,
    { headers: token ? { Authorization: `Bearer ${token}` } : {} },
  );

  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new TranscriptError(
      res.status === 404 ? "NO_TRANSCRIPT" : "PROXY_FAILED",
      `Proxy returned ${res.status}. ${detail.slice(0, 200)}`,
    );
  }

  const data = (await res.json()) as any;
  if (!data?.text) throw new TranscriptError("NO_TRANSCRIPT", "Proxy returned no text.");

  assertUsable(data.text, videoId);
  return {
    text: data.text,
    language: data.language ?? "en",
    isAutoGenerated: !!data.isAutoGenerated,
    provider: "proxy",
    title: data.title,
    author: data.author,
    durationSec: data.durationSec,
    thumbnailUrl: thumb(videoId),
  };
}

/* ---------------------------------------------------------
   Provider 2: direct watch-page HTML scrape

   Works from residential IPs. From Convex's egress this is usually 429 —
   kept because it costs one request and occasionally succeeds when the
   shared IP's budget has refilled.
--------------------------------------------------------- */

/**
 * Walk to the matching close bracket rather than using a lazy `\[.*?\]`, which
 * breaks the first time YouTube nests an array inside a track entry.
 */
function extractCaptionTracks(html: string): CaptionTrack[] {
  const at = html.indexOf('"captionTracks":');
  if (at === -1) return [];
  const start = html.indexOf("[", at);
  if (start === -1) return [];

  let depth = 0;
  let inStr = false;
  let esc = false;
  for (let i = start; i < html.length; i++) {
    const c = html[i];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') inStr = true;
    else if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(start, i + 1));
        } catch {
          return [];
        }
      }
    }
  }
  return [];
}

async function fetchViaWatchPage(videoId: string): Promise<FetchResult> {
  const res = await fetch(
    `${canonicalUrl(videoId)}&hl=en&bpctr=9999999999&has_verified=1`,
    {
      headers: {
        "User-Agent": WEB_UA,
        "Accept-Language": "en-US,en;q=0.9",
        // Skips the EU consent interstitial, which returns a page with no
        // player response at all.
        Cookie: "CONSENT=YES+cb; PREF=hl=en",
      },
    },
  );

  if (!res.ok) {
    throw new TranscriptError(
      res.status === 429 ? "RATE_LIMITED" : "FETCH_BLOCKED",
      `YouTube returned ${res.status} for the watch page.`,
    );
  }

  const html = await res.text();
  const tracks = extractCaptionTracks(html);
  const track = pickTrack(tracks);
  if (!track?.baseUrl) {
    throw new TranscriptError("NO_TRANSCRIPT", "No caption track found on the page.");
  }

  const text = await downloadCaptions(track.baseUrl);
  assertUsable(text, videoId);

  const grab = (re: RegExp) => {
    const m = html.match(re);
    return m ? decodeEntities(m[1]) : undefined;
  };

  return {
    text,
    language: track.languageCode ?? "en",
    isAutoGenerated: track.kind === "asr",
    provider: "watch_page",
    title: grab(/<meta\s+name="title"\s+content="([^"]*)"/),
    author: grab(/"ownerChannelName":\s*"((?:[^"\\]|\\.)*)"/),
    durationSec: Number(html.match(/"lengthSeconds":\s*"(\d+)"/)?.[1]) || undefined,
    thumbnailUrl: thumb(videoId),
  };
}

/* ---------------------------------------------------------
   The chain
--------------------------------------------------------- */

export async function fetchYouTubeTranscript(videoId: string): Promise<FetchResult> {
  const providers: Array<[string, () => Promise<FetchResult>]> = [];
  if (process.env.TRANSCRIPT_PROXY_URL) {
    providers.push(["proxy", () => fetchViaProxy(videoId)]);
  }
  providers.push(["watch_page", () => fetchViaWatchPage(videoId)]);

  const failures: string[] = [];
  let sawRateLimit = false;

  for (const [name, run] of providers) {
    // One retry with jitter: the shared cloud IP's budget sometimes refills.
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        return await run();
      } catch (e) {
        const err = e as TranscriptError;

        // Properties of the video itself — no provider or retry will help.
        if (err.code === "VIDEO_UNAVAILABLE" || err.code === "TRANSCRIPT_TOO_SHORT") {
          throw err;
        }

        if (err.code === "RATE_LIMITED") {
          sawRateLimit = true;
          if (attempt === 0) {
            await new Promise((r) => setTimeout(r, 1200 + Math.random() * 800));
            continue;
          }
        }

        failures.push(`${name}: ${err.message}`);
        break; // next provider
      }
    }
  }

  if (sawRateLimit) {
    throw new TranscriptError(
      "RATE_LIMITED",
      "YouTube is rate-limiting this server's IP. Paste the transcript below to continue — " +
        "or run the local transcript proxy (see README) to fetch from your own IP.",
    );
  }
  if (failures.some((f) => /NO_TRANSCRIPT|no caption/i.test(f))) {
    throw new TranscriptError(
      "NO_TRANSCRIPT",
      "This video has no captions. Paste the transcript below instead.",
    );
  }
  throw new TranscriptError(
    "ALL_PROVIDERS_FAILED",
    `Could not get a transcript. ${failures.join(" | ")}`,
  );
}

/* ---------------------------------------------------------
   Preprocessing — deterministic, free, before any LLM call.
   docs/AI_PIPELINE.md §4
--------------------------------------------------------- */

const FILLERS = [
  "um", "uh", "erm", "you know", "i mean", "sort of", "kind of",
  "basically", "actually", "literally", "like i said", "right\\?",
];
const FILLER_RE = new RegExp(`\\b(?:${FILLERS.join("|")})\\b[,]?\\s*`, "gi");

export function preprocessTranscript(raw: string): string {
  return raw
    .replace(/\[(?:Music|Applause|Laughter|Ambient|Silence)\]/gi, " ")
    .replace(/^>>\s*/gm, "")
    .replace(/^\d{1,2}:\d{2}(:\d{2})?\s*/gm, "") // pasted timestamp gutters
    .replace(FILLER_RE, "")
    .replace(/\b(\w+)(\s+\1\b){2,}/gi, "$1") // "the the the" -> "the"
    .replace(/\s+/g, " ")
    .trim();
}
