#!/usr/bin/env node
/**
 * Local YouTube transcript proxy.
 *
 * WHY THIS EXISTS
 * Two separate walls block fetching captions from Convex:
 *   1. Convex's cloud egress IPs are shared and already rate-limited by
 *      YouTube — the watch page returns 429 almost immediately.
 *   2. More fundamentally, the signed `timedtext` caption URL scraped from the
 *      watch page now returns 200 with an EMPTY body unless the request
 *      carries a PO token. Verified from a clean residential IP across every
 *      format, with cookies and referer. The hand-rolled scrape is dead
 *      everywhere, not just on cloud IPs.
 *
 * yt-dlp solves both: it runs on your machine (residential IP) and is actively
 * maintained against YouTube's countermeasures, including PO tokens.
 *
 * USAGE
 *   brew install yt-dlp                       # or: pipx install yt-dlp
 *   node scripts/transcript-proxy.mjs
 *   cloudflared tunnel --url http://localhost:8799
 *   npx convex env set TRANSCRIPT_PROXY_URL   https://<tunnel-host>
 *   npx convex env set TRANSCRIPT_PROXY_TOKEN <token printed below>
 *
 * Keep yt-dlp current (`yt-dlp -U`). When YouTube changes something, yt-dlp is
 * what gets patched — this script does not need to.
 *
 * No npm dependencies. Node 18+.
 */

import { createServer } from "node:http";
import { execFile } from "node:child_process";
import { randomBytes } from "node:crypto";
import { mkdtemp, readFile, rm, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";

const run = promisify(execFile);

const PORT = Number(process.env.PORT ?? 8799);
const TOKEN = process.env.TRANSCRIPT_PROXY_TOKEN ?? randomBytes(16).toString("hex");
const YTDLP = process.env.YTDLP_PATH ?? "yt-dlp";
const LANG = process.env.SUB_LANG ?? "en";

/** json3 avoids the double HTML-entity encoding the XML format suffers from. */
function parseJson3(raw) {
  const json = JSON.parse(raw);
  return (json.events ?? [])
    .map((e) =>
      (e.segs ?? [])
        .map((s) => s.utf8 ?? "")
        .join("")
        .replace(/\s+/g, " ")
        .trim(),
    )
    .filter(Boolean)
    .join(" ");
}

async function getTranscript(videoId) {
  const dir = await mkdtemp(join(tmpdir(), "mr-sub-"));
  try {
    try {
      await run(
        YTDLP,
        [
          "--skip-download",
          "--ignore-no-formats-error", // subs only; don't fail on SABR-only formats
          "--write-subs",
          "--write-auto-subs",
          "--sub-langs", LANG,
          "--sub-format", "json3",
          "--write-info-json",
          "--no-warnings",
          "--quiet",
          "--no-playlist",
          "-o", join(dir, "%(id)s.%(ext)s"),
          `https://www.youtube.com/watch?v=${videoId}`,
        ],
        { timeout: 90_000, maxBuffer: 1 << 24 },
      );
    } catch (e) {
      const msg = `${e.stderr ?? ""}${e.stdout ?? ""}`.trim() || e.message;
      if (/Private video|members-only|unavailable|removed|age/i.test(msg)) {
        throw Object.assign(new Error("Video is private or unavailable"), { status: 404 });
      }
      if (/Sign in to confirm|bot/i.test(msg)) {
        throw Object.assign(
          new Error("YouTube is bot-checking this machine. Try `yt-dlp -U`, or pass cookies."),
          { status: 429 },
        );
      }
      throw Object.assign(new Error(msg.slice(0, 300)), { status: 502 });
    }

    const files = await readdir(dir);
    const subFile = files.find((f) => f.endsWith(".json3"));
    if (!subFile) {
      throw Object.assign(new Error("No captions available for this video"), { status: 404 });
    }

    const text = parseJson3(await readFile(join(dir, subFile), "utf8"));
    if (!text || text.split(/\s+/).length < 40) {
      throw Object.assign(new Error("Caption track was empty"), { status: 404 });
    }

    let info = {};
    const infoFile = files.find((f) => f.endsWith(".info.json"));
    if (infoFile) {
      try {
        info = JSON.parse(await readFile(join(dir, infoFile), "utf8"));
      } catch {
        /* metadata is a nice-to-have */
      }
    }

    return {
      text,
      language: LANG,
      // yt-dlp prefers a manual track when one exists.
      isAutoGenerated: !info?.subtitles?.[LANG],
      title: info.title,
      author: info.uploader ?? info.channel,
      durationSec: info.duration,
    };
  } finally {
    await rm(dir, { recursive: true, force: true }).catch(() => {});
  }
}

/* --------------------------------------------------------- */

const server = createServer(async (req, res) => {
  const send = (code, body) => {
    res.writeHead(code, { "Content-Type": "application/json" });
    res.end(JSON.stringify(body));
  };

  const url = new URL(req.url, `http://localhost:${PORT}`);
  if (url.pathname === "/health") return send(200, { ok: true });
  if (url.pathname !== "/transcript") return send(404, { error: "not found" });

  if (req.headers.authorization !== `Bearer ${TOKEN}`) {
    return send(401, { error: "bad token" });
  }

  const videoId = url.searchParams.get("videoId");
  if (!videoId || !/^[A-Za-z0-9_-]{11}$/.test(videoId)) {
    return send(400, { error: "valid videoId required" });
  }

  const t0 = Date.now();
  try {
    const data = await getTranscript(videoId);
    console.log(
      `✓ ${videoId}  ${data.text.split(/\s+/).length} words  ${Date.now() - t0}ms  "${data.title ?? ""}"`,
    );
    send(200, data);
  } catch (e) {
    console.log(`✗ ${videoId}  ${e.message}`);
    send(e.status ?? 500, { error: e.message });
  }
});

try {
  await run(YTDLP, ["--version"]);
} catch {
  console.error(
    `\n  yt-dlp not found (looked for "${YTDLP}").\n` +
      `  Install it:  brew install yt-dlp   |   pipx install yt-dlp\n`,
  );
  process.exit(1);
}

server.listen(PORT, () => {
  console.log(`\n  transcript proxy → http://localhost:${PORT}\n`);
  console.log(`  Expose it and point Convex at it:`);
  console.log(`    cloudflared tunnel --url http://localhost:${PORT}`);
  console.log(`    npx convex env set TRANSCRIPT_PROXY_URL   https://<tunnel-host>`);
  console.log(`    npx convex env set TRANSCRIPT_PROXY_TOKEN ${TOKEN}\n`);
});
